version: '3.8'
services:
  openai-email-forward:
    image: xiaotianxt/openai-email-forward:latest
    environment:
      ITS_ID: "${ITS_ID}"
      ITS_PASSWORD: "${ITS_PASSWORD}"
      TZ: Asia/Shanghai
    container_name: forward

